name: UI-Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 17
        - name: Install chrome
          run: sudo apt-get install google-chrome-stable
        - name: Install
          run: npm install
        - name: Test
          run: npm run execute-tests
        - name: Report
          run: npm run clean-report
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: report
            path: | 
              allure-report/
              allure-results/